apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: web
  name: web
spec:
  template:
    metadata:
      labels:
        io.kompose.service: web
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k8s-node-1
                - k8s-node-2
#                - k8s-node-3
#                - k8s-st-node-1
      containers:
      - image: python:3
        name: web
        command: ['sh', '-c', 'python3 -m http.server 5080 & python3 -m http.server 6080']
        ports:
        - containerPort: 5080
        - containerPort: 6080
      restartPolicy: Always
